/**
 * Provider-side contract verification: comments-service
 *
 * Replays the pact generated by the "web-frontend" consumer against the real
 * JSONPlaceholder comments endpoints, confirming the provider still honours
 * every interaction defined in the consumer contract.
 *
 * Prerequisites:
 *   1. Run consumer tests first → npm run test:contract
 *   2. This generates  pacts/web-frontend-comments-service.json
 *   3. Then run        npm run test:provider
 */
import { test } from "@playwright/test";
import { createProviderVerifier } from "../../src/pact/provider-verifier";
import { config } from "../../src/proxy";

const PROVIDER_BASE_URL = config.baseUrl; // https://jsonplaceholder.typicode.com

test.describe("comments-service – Provider Verification @provider", () => {
  test.setTimeout(60_000);

  test("should satisfy all web-frontend consumer contracts", async () => {
    const verifier = createProviderVerifier({
      provider: "comments-service",
      providerBaseUrl: PROVIDER_BASE_URL,
      stateHandlers: {
        "post 1 has comments": async () => {
          // Post 1 has 5 seeded comments in JSONPlaceholder.
          return Promise.resolve();
        },
      },
    });

    await verifier.verifyProvider();
  });
});
