/**
 * Provider-side contract verification: posts-service
 *
 * Replays the pact generated by the "web-frontend" consumer against the real
 * JSONPlaceholder posts endpoints, confirming the provider still honours every
 * interaction defined in the consumer contract.
 *
 * Prerequisites:
 *   1. Run consumer tests first → npm run test:contract
 *   2. This generates  pacts/web-frontend-posts-service.json
 *   3. Then run        npm run test:provider
 */
import { test } from "@playwright/test";
import { createProviderVerifier } from "../../src/pact/provider-verifier";
import { config } from "../../src/proxy";

const PROVIDER_BASE_URL = config.baseUrl; // https://jsonplaceholder.typicode.com

test.describe("posts-service - Provider Verification @provider", () => {
  test.setTimeout(60_000);

  test("should satisfy all web-frontend consumer contracts", async () => {
    const verifier = createProviderVerifier({
      provider: "posts-service",
      providerBaseUrl: PROVIDER_BASE_URL,
      stateHandlers: {
        "a post with ID 1 exists": async () => {
          // Post ID 1 is permanently seeded in JSONPlaceholder.
          return Promise.resolve();
        },
        "the posts service is available": async () => {
          // JSONPlaceholder accepts POST /posts (responds 201, does not persist).
          return Promise.resolve();
        },
      },
    });

    await verifier.verifyProvider();
  });
});
