/**
 * Provider-side contract verification: users-service
 *
 * Replays the pact generated by the "web-frontend" consumer against the real
 * JSONPlaceholder users endpoints, confirming the provider still honours every
 * interaction defined in the consumer contract.
 *
 * Prerequisites:
 *   1. Run consumer tests first → npm run test:contract
 *   2. This generates  pacts/web-frontend-users-service.json
 *   3. Then run        npm run test:provider
 */
import { test } from "@playwright/test";
import { createProviderVerifier } from "../../src/pact/provider-verifier";
import { config } from "../../src/proxy";

const PROVIDER_BASE_URL = config.baseUrl; // https://jsonplaceholder.typicode.com

test.describe("users-service - Provider Verification @provider", () => {
  // Pact replays HTTP interactions; allow enough time for the full suite.
  test.setTimeout(60_000);

  test("should satisfy all web-frontend consumer contracts", async () => {
    const verifier = createProviderVerifier({
      provider: "users-service",
      providerBaseUrl: PROVIDER_BASE_URL,
      stateHandlers: {
        /**
         * JSONPlaceholder is a read-only public API — the data is always
         * present, so state handlers are informational no-ops.
         */
        "a user with ID 1 exists": async () => {
          // User ID 1 (Leanne Graham) is permanently seeded in JSONPlaceholder.
          return Promise.resolve();
        },
        "users exist": async () => {
          // /users always returns 10 users in JSONPlaceholder.
          return Promise.resolve();
        },
      },
    });

    await verifier.verifyProvider();
  });
});
